Docs for klipse integration
cryogen-project/cryogen-docs pull request #16
Opened 2017-01-20 06:16 UTC by madstap

Docs explaining how to set up klipse. They probably need some work, and I would appreciate some feedback on how easy to understand they are.

2017-01-31 03:32 UTC, lacarmen requested changes

2017-01-31 03:32 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +You configure the klipse plugin in `config.edn` and set `:klipse` to `true` in the post metadata.
"post metadata" -> "post or page metadata"

2017-01-31 03:32 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +In cryogen you can use `:lisp-cased-keywords` instead of `"snake_cased_strings"`.
> In cryogen you can use `:lisp-cased-keywords` instead of `"snake_cased_strings"`.

I found this sentence confusing when I first read it. I think you can remove it and update the previous sentence to say "Contains a **Clojure** map [...]". This should be sufficient when combined with the config example below.

2017-01-31 03:32 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +Alternatively you can override specific settings in the post metadata by passing a map.
>Alternatively you can override parts of the global settings by passing a `:settings` map (described below) containing the desired changes to the `:klipse` key in the post/page metadata.

I think this sounds less ambiguous.

2017-01-31 03:32 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +Lorem ipsum etc.
You should add an example of a klipse-enabled code block to this post as well as the one below and make it clear that you have to embed your code in a markdown tag that matches the associated   Klipse selector. (In this case `klipse-cljs`)

Something like:

\```klipse-cljs
(apply + (range 0 11))
\```

2017-02-01 15:04 UTC, madstap commented on resources/templates/md/docs/klipse.md
> +Lorem ipsum etc.
Yeah, I agree. Markdown-clj didn't support nested code blocks like that though, but version 0.9.94 does. I made a pull request to cryogen-markdown to bump the versions. cryogen-project/cryogen-markdown#8

2017-02-01 15:10 UTC, madstap commented on resources/templates/md/docs/klipse.md
> +In cryogen you can use `:lisp-cased-keywords` instead of `"snake_cased_strings"`.
I added the __clojure__ map wording, but I would argue that it's obvious that you can use keywords, but not that it translates from kebab-case to underscores/camelCase as necessary. It's understandable by looking at the examples, but I still like things spelled out. I put it in parentheses and added some spacing, which I feel improved it. I'll remove it if you feel like it's still confusing/unnecessary.

2017-02-01 19:13 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +In cryogen you can use `:lisp-cased-keywords` instead of `"snake_cased_strings"`.
Sure, that sounds less confusing.

2017-02-01 19:17 UTC, lacarmen commented on resources/templates/md/docs/klipse.md
> +Lorem ipsum etc.
I deployed the new version and updated the dependency in this project.

2017-02-02 03:27 UTC, lacarmen approved these changes

2017-02-02 03:32 UTC, merged