Add page customizing-cryogen
cryogen-project/cryogen-docs pull request #26
Opened 2019-12-06 21:31 UTC by holyjak

Any comments / improvements? Perhaps move it elsewhere in the docs structure?

2019-12-08 15:23 UTC, lacarmen requested changes
Just need some minor changes.

This is a great start! We could always create a dedicated "Customizing Cryogen" heading if more options/tricks become available in the future.

2019-12-08 15:23 UTC, lacarmen commented on resources/templates/md/docs/customizing-cryogen.md
> +{:title "Customizing Cryogen"
Maybe change to "Customizing/Extending Cryogen"?

2019-12-08 15:23 UTC, lacarmen commented on resources/templates/md/docs/customizing-cryogen.md
> + :section "Additional Resources"}
Should add `:toc` to this page :)

2019-12-08 15:23 UTC, lacarmen commented on resources/templates/md/docs/customizing-cryogen.md
> +You can copy the `cryogen-core.compiler` namespace directly into your project (where it will override the one from the cryogen-core.jar) and modify it to your liking. It is not very long or complicat
We should add a quick disclaimer at the end here: "Although this site is generated using a much older version of `cryogen-core`, you may still use the same strategy today"

I feel like people might wonder about that 😛

2019-12-09 10:42 UTC, holyjak commented
Comments addressed.

2019-12-09 15:43 UTC, lacarmen approved these changes
Awesome, looks great!

2019-12-09 15:43 UTC, merged